---
title: "Testing_Ch4"
author: "Jethro Infante"
date: "2023-10-04"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(tidyverse)
library(rpart)
library(rpart.plot)
library(randomForest)
library(tidyverse)
```

```{r}
# Specify the file path to your CSV file, change path as needed
rank_file <- "jackson_data.csv"
bball_file <- "jethro_victor_data.csv"

# Read the CSV file into a dataframe
rank_data <- read_csv(show_col_types = FALSE, rank_file)
bball_data <- read_csv(show_col_types = FALSE, bball_file)
rank_data
bball_data
```
```{r}
# Create a new column based on days since last game
bball_data <- bball_data %>%
  mutate(PrevGameDate = as.Date(PrevGameDate),
         gameDate = as.Date(gameDate),
         DaysSincePrevGame = as.numeric(gameDate - PrevGameDate))

# Define the number of bins and their labels
num_bins <- 5  # You can adjust this as needed
bin_labels <- c("Low", "Moderate", "Good", "Great", "Excellent")

# Create bins for the "PTS" column
bball_data <- bball_data %>%
  mutate(PTS_Bins = cut(PTS, breaks = num_bins, labels = bin_labels))

bball_data
```


```{r}
dtree <- rpart(Team_Won ~ MIN + PrevGameMin + DaysSincePrevGame + seasonPart, data = bball_data)
rpart.plot(dtree)
```

Below we will need to modify the code so that it works with our dataset, or whatever it is we're looking for.

```{r}
bball_train_ind <- sample(1:nrow(bball_data), size = floor(0.8*nrow(bball_data)))

dtree <- rpart(Team_Won ~ ., data = bball_data[bball_train_ind,])
rpart.plot(dtree)
pred_bball <- predict(dtree, bball_data[-bball_train_ind,])
table(bball_data[-bball_train_ind,]$class, colnames(pred_bball)[if_else(pred_bball[,1] > pred_bball[,2], 1, 2)])
print(dtree$splits)

dtree <- rpart(Team_Won ~ MIN + FG_PCT + FG3_PCT + FT_PCT + REB + AST + STL + BLK + PTS + PrevGameMin ,
               data = bball_data[bball_train_ind,])
rpart.plot(dtree)
pred_bball <- predict(dtree, bball_data[-bball_train_ind,])
table(bball_data[-bball_train_ind,]$class, colnames(pred_bball)[if_else(pred_bball[,1] > pred_bball[,2], 1, 2)])
print(dtree$splits)
```
